# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9d21c86592aa1edf058a5554a60dcb160692c46093e07a50ccb44f3bab6a248efc8b01cb7eb6675b4b13dd93c4f6829cb67f17d7ad4fe03c3713d43df9f95aa

test:
  secret_key_base: 30cf9abaf26760b68fa832b8e512a1dd7d42d365334c6b50e2d523d239356bde70a0abe8c1c57d4f8a9285c6c52f27e929abf18d7d0c91b31cc3ab838f5d702c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
